// Code generated by MockGen. DO NOT EDIT.
// Source: favorites_port.go
//
// Generated by this command:
//
//	mockgen -source=favorites_port.go -destination=../test/mocks/favorites_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/moondolphin/crypto-api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFavoritesRepository is a mock of FavoritesRepository interface.
type MockFavoritesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFavoritesRepositoryMockRecorder
	isgomock struct{}
}

// MockFavoritesRepositoryMockRecorder is the mock recorder for MockFavoritesRepository.
type MockFavoritesRepositoryMockRecorder struct {
	mock *MockFavoritesRepository
}

// NewMockFavoritesRepository creates a new mock instance.
func NewMockFavoritesRepository(ctrl *gomock.Controller) *MockFavoritesRepository {
	mock := &MockFavoritesRepository{ctrl: ctrl}
	mock.recorder = &MockFavoritesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoritesRepository) EXPECT() *MockFavoritesRepositoryMockRecorder {
	return m.recorder
}

// AddFavoriteCoinToUser mocks base method.
func (m *MockFavoritesRepository) AddFavoriteCoinToUser(ctx context.Context, userID, coinID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavoriteCoinToUser", ctx, userID, coinID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFavoriteCoinToUser indicates an expected call of AddFavoriteCoinToUser.
func (mr *MockFavoritesRepositoryMockRecorder) AddFavoriteCoinToUser(ctx, userID, coinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavoriteCoinToUser", reflect.TypeOf((*MockFavoritesRepository)(nil).AddFavoriteCoinToUser), ctx, userID, coinID)
}

// ListFavoriteCoinIDsByUser mocks base method.
func (m *MockFavoritesRepository) ListFavoriteCoinIDsByUser(ctx context.Context, userID int64) ([]domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoriteCoinIDsByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavoriteCoinIDsByUser indicates an expected call of ListFavoriteCoinIDsByUser.
func (mr *MockFavoritesRepositoryMockRecorder) ListFavoriteCoinIDsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoriteCoinIDsByUser", reflect.TypeOf((*MockFavoritesRepository)(nil).ListFavoriteCoinIDsByUser), ctx, userID)
}

// RemoveFavoriteCoinFromUser mocks base method.
func (m *MockFavoritesRepository) RemoveFavoriteCoinFromUser(ctx context.Context, userID, coinID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavoriteCoinFromUser", ctx, userID, coinID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFavoriteCoinFromUser indicates an expected call of RemoveFavoriteCoinFromUser.
func (mr *MockFavoritesRepositoryMockRecorder) RemoveFavoriteCoinFromUser(ctx, userID, coinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavoriteCoinFromUser", reflect.TypeOf((*MockFavoritesRepository)(nil).RemoveFavoriteCoinFromUser), ctx, userID, coinID)
}
