// Code generated by MockGen. DO NOT EDIT.
// Source: price_port.go
//
// Generated by this command:
//
//	mockgen -source=price_port.go -destination=../test/mocks/price_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/moondolphin/crypto-api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPriceProvider is a mock of PriceProvider interface.
type MockPriceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPriceProviderMockRecorder
	isgomock struct{}
}

// MockPriceProviderMockRecorder is the mock recorder for MockPriceProvider.
type MockPriceProviderMockRecorder struct {
	mock *MockPriceProvider
}

// NewMockPriceProvider creates a new mock instance.
func NewMockPriceProvider(ctrl *gomock.Controller) *MockPriceProvider {
	mock := &MockPriceProvider{ctrl: ctrl}
	mock.recorder = &MockPriceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceProvider) EXPECT() *MockPriceProviderMockRecorder {
	return m.recorder
}

// GetCurrentPrice mocks base method.
func (m *MockPriceProvider) GetCurrentPrice(ctx context.Context, coin domain.Coin, currency string) (domain.PriceQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice", ctx, coin, currency)
	ret0, _ := ret[0].(domain.PriceQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockPriceProviderMockRecorder) GetCurrentPrice(ctx, coin, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockPriceProvider)(nil).GetCurrentPrice), ctx, coin, currency)
}

// Name mocks base method.
func (m *MockPriceProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPriceProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPriceProvider)(nil).Name))
}

// MockPriceProviderRegistry is a mock of PriceProviderRegistry interface.
type MockPriceProviderRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPriceProviderRegistryMockRecorder
	isgomock struct{}
}

// MockPriceProviderRegistryMockRecorder is the mock recorder for MockPriceProviderRegistry.
type MockPriceProviderRegistryMockRecorder struct {
	mock *MockPriceProviderRegistry
}

// NewMockPriceProviderRegistry creates a new mock instance.
func NewMockPriceProviderRegistry(ctrl *gomock.Controller) *MockPriceProviderRegistry {
	mock := &MockPriceProviderRegistry{ctrl: ctrl}
	mock.recorder = &MockPriceProviderRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceProviderRegistry) EXPECT() *MockPriceProviderRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPriceProviderRegistry) Get(name string) (domain.PriceProvider, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(domain.PriceProvider)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPriceProviderRegistryMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPriceProviderRegistry)(nil).Get), name)
}
