// Code generated by MockGen. DO NOT EDIT.
// Source: quote_filters.go
//
// Generated by this command:
//
//	mockgen -source=quote_filters.go -destination=../test/mocks/quote_filters_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
