// Code generated by MockGen. DO NOT EDIT.
// Source: quote_filter.go
//
// Generated by this command:
//
//	mockgen -source=quote_filter.go -destination=../test/mocks/quote_filter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
