// Code generated by MockGen. DO NOT EDIT.
// Source: quote_port.go
//
// Generated by this command:
//
//	mockgen -source=quote_port.go -destination=../test/mocks/quote_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/moondolphin/crypto-api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQuoteRepository is a mock of QuoteRepository interface.
type MockQuoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuoteRepositoryMockRecorder
	isgomock struct{}
}

// MockQuoteRepositoryMockRecorder is the mock recorder for MockQuoteRepository.
type MockQuoteRepositoryMockRecorder struct {
	mock *MockQuoteRepository
}

// NewMockQuoteRepository creates a new mock instance.
func NewMockQuoteRepository(ctrl *gomock.Controller) *MockQuoteRepository {
	mock := &MockQuoteRepository{ctrl: ctrl}
	mock.recorder = &MockQuoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuoteRepository) EXPECT() *MockQuoteRepositoryMockRecorder {
	return m.recorder
}

// GetLatest mocks base method.
func (m *MockQuoteRepository) GetLatest(ctx context.Context, symbol, provider, currency string) (*domain.PriceQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, symbol, provider, currency)
	ret0, _ := ret[0].(*domain.PriceQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockQuoteRepositoryMockRecorder) GetLatest(ctx, symbol, provider, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockQuoteRepository)(nil).GetLatest), ctx, symbol, provider, currency)
}

// Insert mocks base method.
func (m *MockQuoteRepository) Insert(ctx context.Context, q domain.Quote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockQuoteRepositoryMockRecorder) Insert(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQuoteRepository)(nil).Insert), ctx, q)
}

// ListFilter mocks base method.
func (m *MockQuoteRepository) ListFilter(ctx context.Context, f domain.QuoteFilter) ([]domain.Quote, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilter", ctx, f)
	ret0, _ := ret[0].([]domain.Quote)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFilter indicates an expected call of ListFilter.
func (mr *MockQuoteRepositoryMockRecorder) ListFilter(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilter", reflect.TypeOf((*MockQuoteRepository)(nil).ListFilter), ctx, f)
}
