// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_control_port.go
//
// Generated by this command:
//
//	mockgen -source=refresh_control_port.go -destination=../test/mocks/refresh_control_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshControlRepository is a mock of RefreshControlRepository interface.
type MockRefreshControlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshControlRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshControlRepositoryMockRecorder is the mock recorder for MockRefreshControlRepository.
type MockRefreshControlRepositoryMockRecorder struct {
	mock *MockRefreshControlRepository
}

// NewMockRefreshControlRepository creates a new mock instance.
func NewMockRefreshControlRepository(ctrl *gomock.Controller) *MockRefreshControlRepository {
	mock := &MockRefreshControlRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshControlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshControlRepository) EXPECT() *MockRefreshControlRepositoryMockRecorder {
	return m.recorder
}

// GetLastManualRefresh mocks base method.
func (m *MockRefreshControlRepository) GetLastManualRefresh(ctx context.Context) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastManualRefresh", ctx)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastManualRefresh indicates an expected call of GetLastManualRefresh.
func (mr *MockRefreshControlRepositoryMockRecorder) GetLastManualRefresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastManualRefresh", reflect.TypeOf((*MockRefreshControlRepository)(nil).GetLastManualRefresh), ctx)
}

// SetLastManualRefresh mocks base method.
func (m *MockRefreshControlRepository) SetLastManualRefresh(ctx context.Context, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastManualRefresh", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastManualRefresh indicates an expected call of SetLastManualRefresh.
func (mr *MockRefreshControlRepositoryMockRecorder) SetLastManualRefresh(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastManualRefresh", reflect.TypeOf((*MockRefreshControlRepository)(nil).SetLastManualRefresh), ctx, t)
}
